export const questions = [
    {id:"191740014982", title:"Mouse Konumu Hesaplama", text:"merhaba yine ben, mouse'un şimdiki konumuna göre bir sonraki framedeki konumunu nasıl tespit edebiliriz. Şunu yapmak istiyorum aslında mouse'um sağa mı gidiyor sola mı gidiyor onu tespit etmek istiyorum. teşekkürler.", name:"talihoz", language:"c", responses:2},
    {id:"191740910240", title:"Mouse Konumu Hesaplama", text:"merhaba yine ben, mouse'un şimdiki konumuna göre bir sonraki framedeki konumunu nasıl tespit edebiliriz. Şunu yapmak istiyorum aslında mouse'um sağa mı gidiyor sola mı gidiyor onu tespit etmek istiyorum. teşekkürler.", name:"talihoz", language:"p5js", responses:2},
    {id:"853908325923", title:"p5js Sound Ekleme", text:"merhaba sound eklemeye çalışıyorum hatta direk örnek kodu kopyalayıp kendi bilgisayarımdaki bir mp3 ile deniyorum ama sürekli error veriyor. Mp3 ü masaüstüne kaydettim. Sorun ne olabilir", name:"serrakeklik", language:"java", responses:4},
    {id:"581205893205", title:"WebGL sonsuz loop", text:"Merhaba bende daha önce paylaşılan bir kaynakta bunu gördüm de p5js de nasıl çizeriz diye düşünmeye başladım. Silindir for ve rotatele yapılabilir gibi geldi ancak silindirin farklı yüzeylerini farklı renklere boyanabiliyor mu?", name:"ozge_suv", language:"javascript", responses:5},
    {id:"229835853993", title:"WebGL sonsuz loop", text:"Merhaba bende daha önce paylaşılan bir kaynakta bunu gördüm de p5js de nasıl çizeriz diye düşünmeye başladım. Silindir for ve rotatele yapılabilir gibi geldi ancak silindirin farklı yüzeylerini farklı renklere boyanabiliyor mu?", name:"ozge_suv", language:"react", responses:5},
    {id:"571820935897", title:"p5js Sound Ekleme", text:"merhaba sound eklemeye çalışıyorum hatta direk örnek kodu kopyalayıp kendi bilgisayarımdaki bir mp3 ile deniyorum ama sürekli error veriyor. Mp3 ü masaüstüne kaydettim. Sorun ne olabilir", name:"serrakeklik", language:"python", responses:4},
    {id:"892553893859", title:"WebGL sonsuz loop", text:"Merhaba bende daha önce paylaşılan bir kaynakta bunu gördüm de p5js de nasıl çizeriz diye düşünmeye başladım. Silindir for ve rotatele yapılabilir gibi geldi ancak silindirin farklı yüzeylerini farklı renklere boyanabiliyor mu?", name:"ozge_suv", language:"cpp", responses:5},
    {id:"795821328583", title:"Mouse Konumu Hesaplama", text:"merhaba yine ben, mouse'un şimdiki konumuna göre bir sonraki framedeki konumunu nasıl tespit edebiliriz. Şunu yapmak istiyorum aslında mouse'um sağa mı gidiyor sola mı gidiyor onu tespit etmek istiyorum. teşekkürler.", name:"talihoz", language:"go", responses:2},
    {id:"193807597533", title:"p5js Sound Ekleme", text:"merhaba sound eklemeye çalışıyorum hatta direk örnek kodu kopyalayıp kendi bilgisayarımdaki bir mp3 ile deniyorum ama sürekli error veriyor. Mp3 ü masaüstüne kaydettim. Sorun ne olabilir", name:"serrakeklik", language:"rust", responses:4},
]

export const answers = [
    "Bugün derste sorulan mouse imlecini takip eden obje için bir örnek yaptım. Derste bahsedildiği gibi burada asıl işi atan2() fonksiyonu üstleniyor.",
    "Bilgisayardaki mp3'u editor’deki klasore yuklemek gerekiyor olabilir.",
    "Bunun icin uc boyutlu primitive’ler kullanilabili. Bir de iki farkli animasyon arasinda geciyoruz sanki. Bir animasyon krem silindirlerlerden yapilma, digeri de lacivertlerden. Ikisinin arasinda/ortasinda da lacivert krem karelerden olusan tek bir sahne var gibi. Baglantida golgesiz 3d nesne yapmanin ornegi var: https://editor.p5js.org/vidianindhita/sketches/H13K5pF3Z"
]